BEGIN;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS movements CASCADE; 
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
COMMIT;
